### ISSUE TITLE
Error when executing the worflow

### ISSUE THREAD

**Issue by razvantim** [mindrevolution/Contour-Delete-Record-Workflow#1]
After each execution of the workflow (in the approved event) I receive this error 

The INSERT statement conflicted with the FOREIGN KEY constraint FK_UFRecordDataString_UFRecordFields. The conflict occurred in database, table dbo.UFRecordFields, column 'Key'.\r\nThe statement has been terminated.

Contour version 3.0.21

**Comment by MarcStoecker** [comment]
I haven't used the workflow with this version, sorry. Is this on v6 or v7?

**Comment by ghost** [comment]
I have the same issue. This is on v7.

**Comment by amirkhan81** [comment]
Any updated on whether this works on v7 or with the new Umbraco Forms?

**Comment by MarcStoecker** [comment]
Neither checked. But I think we have this requirement for an upcoming project due in Dec. Will check with my coworkers (i.e. @dmerkle) if they will revive it or not.

**Comment by amirkhan81** [comment]
Hi, any word on whether you'll be reviving this workflow?

**Comment by MarcStoecker** [comment]
Yes, we will. No word on the date yet, but Dec/Jan is still the timeframe.

**Comment by amirkhan81** [comment]
Hi, just checking on if this was released?

**Comment by MarcStoecker** [comment]
Just in case somebody finds this thread while googling: **Umbraco Forms supports this OOTB now.**
